name: golangci-lint
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        working-directory:
          - ""
          - "virtualcluster"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.17
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          version: v1.47.2
          working-directory: ${{matrix.working-directory}}
